server:
  port: 8082

application:
  title: Edu Matrix Management
  version: (0.0.1)

spring:
  application:
    name: EDU-MATRIX-DISCOVERY-SERVICE
  cloud:
    gateway:
      server:
        webflux:
          enabled: false
eureka:
  instance:
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://172.25.208.1:8082/eureka/



