server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.139:8082/eureka/

spring:
  application:
    name: EDU-GATEWAY-SERVICE

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:4200
            - AddResponseHeader=Access-Control-Allow-Credentials, true
          globalcors:
            corsConfigurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:4200"
                allowedHeaders: "*"
                allowedMethods: "*"
                allow-credentials: true
          routes:
            - id: security-service-route
              uri: lb://EDU-MATRIX-SECURITY/
              predicates:
                - Path=/security/api/**

  main:
    web-application-type: reactive
